### ISSUE TITLE
ENH: Allow videos to be iterable.

### ISSUE THREAD

**Issue by masasin** [anbergem/cvhelper#6]
There's a function to iterate over all the frames in a video, but it would be much prettier to just `for frame in video:` directly, especially if you're already controlling what you're getting using the context manager.

**Comment by anbergem** [comment]
Great proposal! My first thought is that this would have to be done by extending the `cv2.VideoCapture` class, adding an `__iter__` method. Any inputs on this?

I'm currently developing tests, but I'll be sure to add this soon!
